### ISSUE TITLE
Improve the console output

### ISSUE THREAD

**Issue by PunKeel** [docbleach/DocBleach#3]
Linked issue: #2 
As of now, the amount of potentiel threats removed is the only displayed information.

Having two output formats would be fine, with a toggle: 👨 (textual) & 🤖  (json).

Nice informations to include:
For the 👨 display, name & location of the threat ("Macro executed when the document is opened", "Active.X object in the 2nd page" ....), list of the removed content
For the 🤖 output: same thing, with internal data?

**Comment by vmalguy** [comment]
This output should be sent to syslog instead/before output

**Comment by PunKeel** [comment]
Commit 43a516b adds a json output option, I'll consider this issue closed

The output (json/log) is sent to STDERR by SLF4J, sending it to syslog seems weird to me as this is not a daemon (for now, atleast)
