### ISSUE TITLE
sanitized PDF more than doubles in size

### ISSUE THREAD

**Issue by rhuddleston** [docbleach/DocBleach#34]
When I run docbleach over a file used for testing the file size more than doubles. 

I got this file from here https://blog.didierstevens.com/2015/08/28/test-file-pdf-with-embedded-doc-dropping-eicar/

In this case the PDF has an embedded file and a JavaScript launcher. DocBleach removed the JavaScript launcher but The embedded file became much larger.

**Comment by PunKeel** [comment]
Hi,
Sorry for the delay and thanks for reporting this issue, and extra thanks for providing the test file!

762f5c5 should help with this scenario, and for the test file the size is reduced: 

```
10K pdf-doc-vba-eicar-dropper.pdf
6.4K after-docbleach.pdf
```
