### ISSUE TITLE
-Batch parameter gone in v0.0.3

### ISSUE THREAD

**Issue by joesecurity** [docbleach/DocBleach#7]
Batch parameter gone.

**Comment by PunKeel** [comment]
Hello,
I removed the -batch parameter in v0.0.2 because it was unused, except in the PDF Bleach to ask for a password.

I don't think keeping it is a good idea, as the default behaviour should be "batch" by default I think.

If you specifically need it, just tell me and I'll see what can be done

**Comment by joesecurity** [comment]
Ack! If there are no queries then batch mode is not needed!
